### ISSUE TITLE
Create index.d.ts

### ISSUE THREAD

**Issue by SoaresMG** [eadmundo/redux-seamless-immutable#11]
Hi,

Is it ok if I create a definition file for typescript and add it to the [@types](https://github.com/DefinitelyTyped/DefinitelyTyped) global repo?

Thank you.

**Comment by eadmundo** [comment]
Hi @SoaresMG - absolutely, all contributions welcomed! However I should give you a heads up that we are rebuilding this and moving the maintained version to our https://github.com/autotelic/ org in the next week or so, so if it's not super urgent might be easier to wait for that version? Up to you, we are happy to review PRs and port across.

**Comment by eadmundo** [comment]
Sorry I misunderstood slightly there (not a TypeScript person). I think we are fine with you adding that to the global repo - are there any implications of that we should be aware of? I don't know if the org move will make any difference, other than the type definitions might need to change as we are refactoring a bit as well...

**Comment by eadmundo** [comment]
@HW13 thoughts?

**Comment by SoaresMG** [comment]
Hey @eadmundo, there are no implications by doing this.

I can maintain that file whenever the definitions change. 

I will use the same semver as you, so if you are using this repo's 1.0.2 version you should also use @types/redux-seamless-immutable@1.0.2

I already created the file, just wanted your permission for this.

**Comment by eadmundo** [comment]
Appreciate the heads-up! Go for it 🙂

**Comment by SoaresMG** [comment]
Hey! I got a bit of time to do this.

Here is the [@types PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33989)

**Comment by SoaresMG** [comment]
It got merged 10 days ago.

**Comment by eadmundo** [comment]
Awesome, thanks @SoaresMG 👍
